polkit: Fix the fetch problem for v122
meta-openembedded introduce the fetch problem as
ERROR: polkit-122-r0 do_fetch: Bitbake Fetcher Error:
      FetchError('Unable to fetch URL from any source.',
         'git://github.com/freedesktop/polkit.git;protocol=https;branch=master')

Signed-off-by: Jun Zhu <junzhu@nxp.com>