Revert "firmware-nxp-wifi_%.bbappend: Improvement recipe"
This change breaks on whinlatter:
```
+ bitbake -k fsl-image-networking-full
ERROR: Nothing RPROVIDES 'firmware-nxp-wifi-all-sdio' (but /.../sources/meta-qoriq/meta-qoriq-sdk/recipes-fsl/packagegroups/packagegroup-fsl-tools-extended.bb RDEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'firmware-nxp-wifi-all-pcie' (but /.../sources/meta-qoriq/meta-qoriq-sdk/recipes-fsl/packagegroups/packagegroup-fsl-tools-extended.bb RDEPENDS on or otherwise requires it)
```

This reverts commit da985d33c02c55a097a68e58d85be789cc8e813d.