dce: add bbappend to fix gcc10 build
The variable 'qman_version' is defined in the header file qbman_portal.h,
if multiple C files include qbman_portal.h the compiler complaint for
multiple definition of 'qman_version'.

To fix multiple definition error, move the definition of 'qman_version'
into qbman_portal.c and qbman_debug.c.

| .../dce/git-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/10.2.0/ld: libqbman.a(qbman_portal.o):/usr/src/debug/dce/git-r0/git/lib/qbman_userspace/driver/qbman_portal.h:36: multiple definition of `qman_version'; libqbman.a(qbman_debug.o):/usr/src/debug/dce/git-r0/git/lib/qbman_userspace/driver/qbman_portal.h:36: first defined here
| collect2: error: ld returned 1 exit status
| Makefile:41: recipe for target 'bin/dce-api-perf-test' failed
| make: *** [bin/dce-api-perf-test] Error 1

Signed-off-by: Ting Liu <ting.liu@nxp.com>