optee-test-qoriq: suppress deprecated-declarations error
Fix below build error with openssl 3.0:
.../host/xtest/regression_8100.c: In function 'osslerr':
.../host/xtest/regression_8100.c:131:17: error: 'ERR_get_error_line' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  131 |                 e = ERR_get_error_line(&f, &l);
      |                 ^
In file included from .../host/xtest/regression_8100.c:18:
.../recipe-sysroot/usr/include/openssl/err.h:411:15: note: declared here
  411 | unsigned long ERR_get_error_line(const char **file, int *line);
      |               ^~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Signed-off-by: Ting Liu <ting.liu@nxp.com>