meta-qoriq: fix optee-client-qoriq build issue
There has been a change in optee-client on upstream
which is causing build failure.

Getting following issue:

ERROR: optee-client-qoriq-4.4.0+git-r0 do_package: QA Issue:
  optee-client-qoriq: Files/directories were installed but not
  shipped in any package:
  /usr/lib/systemd
  /usr/lib/systemd/system
  /usr/lib/systemd/system/tee-supplicant@.service

optee-client src is installing the tee-supplicant@.service file.

For fixing the builds as a workaround updating the optee-client-qoriq.inc
to remove the files.

Signed-off-by: Sahil Malhotra <sahil.malhotra@nxp.com>