libpkcs11: remove conflicting pkcs11.h
Error: Transaction test error:
  file /usr/include/pkcs11.h conflicts between attempted installs of libpkcs11-dev-git-r0.aarch64 and optee-client-qoriq-dev-3.10.0+git0+2a77cf88d9-r0.aarch64

Signed-off-by: Ting Liu <ting.liu@nxp.com>