layer.conf:debug-tweaks image feature is now removed from walnascar
Fix error:
ERROR: Nothing PROVIDES 'core-image-minimal'
core-image-minimal was skipped: 'debug-tweaks' in IMAGE_FEATURES

Signed-off-by: Zelan Zou <zelan.zou@nxp.com>