polkit: add bbappend to rm empty rules.d
Fix:
Error: Transaction check error:
file /usr/share/polkit-1/rules.d conflicts between attempted installs of libvirt-5.5.0-r0.aarch64 and polkit-0.116-r0.aarch64

Signed-off-by: Ting Liu <ting.liu@nxp.com>