perf.bbappend: Include sample.h for 32bit platform build [LF-12965]
python.c is used to build perf's source code, arm32 kenel toolchian can not
found sample.h and cause build break like:

| python.c:69:49: error: invalid use of undefined type 'struct perf_sample'

Signed-off-by: Zelan Zou <zelan.zou@nxp.com>