fsl-image-mfgtool.bb: Remove install fmc in Upstream kernel
linux-nxp-rebase kernel no fm_ioctls.h head file, which cause fmlib build break:
| src/fm_lib.c:54:10: fatal error: fm_ioctls.h: No such file or directory
|    54 | #include "fm_ioctls.h"|
|          ^~~~~~~~~~~~~
| compilation terminated.
| ERROR: oe_runmake failed

fmlib was depended on fmc, which install in fsl-image-mfgtools rootfs.
qoriq-composite-firmware would use fsl-image-mfgtools to build out kernelitb and firmware_xxx.img
Signed-off-by: Zelan Zou <zelan.zou@nxp.com>