optee-client.nxp.inc: Fix bash-spcific programming commandline [LF-7657]
When use Dash and set INIT_MANAGER = "systemd", it breaks as
 ERROR: optee-client-qoriq-3.17.0+gitAUTOINC+9d8f1903bb-r0 do_package:
 Didn't find service unit 'tee-supplicant.service', specified in SYSTEMD_SERVICE:optee-client-qoriq.

Signed-off-by: Jun Zhu <junzhu@nxp.com>